name: Build iOS dylib

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          export THEOS="$HOME/theos"
          echo "THEOS=$THEOS" >> "$GITHUB_ENV"

          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Check project
        run: |
          echo "Project files:"
          find . -maxdepth 2 -type f | sort

          echo
          echo "Theos:"
          ls -la "$THEOS"

      - name: Build dylib
        run: |
         export THEOS=/Users/runner/theos
         export TARGET=iphone:clang:latest:13.0
         export ARCHS="arm64 arm64e"
         make clean
         make

      - name: Find dylib
        run: |
          find . -type f -name "*.dylib" -print

      - name: Prepare artifact
        run: |
          mkdir -p build

          DYLIB="$(find . -type f -name '*.dylib' \
            -not -path './build/*' \
            -print -quit)"

          if [ -z "$DYLIB" ]; then
            echo "ERROR: dylib was not generated"
            exit 1
          fi

          cp "$DYLIB" build/MyDylib.dylib

          if [ -f cache_res ]; then
            cp cache_res build/cache_res
          fi

      - name: Verify dylib
        run: |
          file build/MyDylib.dylib
          otool -L build/MyDylib.dylib

      - name: Package
        run: |
          cd build
          zip -r ../MyDylib-iOS.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDylib-iOS
          path: MyDylib-iOS.zip
